### PR TITLE
Vagrantfile for using `vagrant up`

### PR DESCRIPTION
**Pull request by kzap**
A Vagrantfile for setting up Shinobi using Vagrant and Virtualbox with a single command

### CODE REVIEW

**Comment by kzap** [comment]
run `vagrant up` from the working directory
and then once its done just go to `http://shinobi.dev:8080/ and its working

**Comment by moeiscool** [comment]
i see something about apache in there, whats that for? does it install apache2 also? can it be removed? since Shinobi uses express framework. or is there a need for it? sorry I've never used Vagrantfiles before.

and that is a lot of files, can we .gitignore any of them?

**Comment by kzap** [comment]
the main files changes are 
`Vagrantfile` <-- the main file that Vagrant uses
`vagrant/` <-- contains all the files that are used to setup/configure the VM
and renamed `config.json` to `config.sample.json` since its an environment file and would keep on being overwritten everytime we update.

**Comment by kzap** [comment]
apache is setup on the VM to use phpMyAdmin to administer the database and maybe other web stuff that doesnt run on node

i'll try to slim it down by not including the phpMyAdmin files and just making it download and install them

**Comment by kzap** [comment]
ok whittled it down to 58 files

rebased with latest `master`

**Review by moeiscool — COMMENTED** [review]
sweeeeeeeeeeeeeeeeet

**Comment by kzap** [comment]
I should probably add instructions to the readme on how to use this

**Pull request merged**
