### PR TITLE
Add subtitle stream if vcodec is copy

### PR DESCRIPTION
**Pull request by mattdurant**
Instead of not being able to overlay a timestamp onto video streams in copy mode, on video complete I generate an SRT file and exec ffmpeg to add it to the container.  Most video players will support it as a cheap way to have the timestamp available on these streams. 

If this is acceptable, we can also generate VTT files and keep them with the videos so that the html5 viewer can show the same timestamps?  For compliance with LEO, could add a way to pull the SRT stream back out and permanently overlay it since it's CPU intensive to burn them in.

### CODE REVIEW

**Comment by moeiscool** [comment]
Please rebase i can't see the comparison :sweat_smile:. Please ensure only relevant commits appear in your pull request.

**Comment by moeiscool** [comment]
also no pull requests should be made to master. Only to the dev branch please.

**Comment by moeiscool** [comment]
just clicked on one commit and seeing a lot of `writeSync`.. please change this to async because of where you are executing this it may cause hangs.

It would also be preferable to add this as an option instead of only being allowed to use it when copy is active. So we can choose to use the video filter or the SRT.

**Comment by mattdurant** [comment]
My mistake on creating the PR for the master branch, GitHub changes that back every time I change any other dropdowns when making one...

I probably need to use createWriteStream when generating the SRT instead of writeFile and a bunch of callbacks.  I'll work on adding it as a selectable option and then submit it all again as one PR.

**Comment by moeiscool** [comment]
also you can't write or change the videos folder while shinobi is running. You will probably end up with a lot of damaged SQL rows. Only the video file being written by ffmpeg (the original one) should be the one writing there.

Is there a way not to have to open another ffmpeg at all to use the SRT? Even using javascript would be okay with me.

**Comment by mattdurant** [comment]
The end result leaves a file with the exact same filename that was already there to begin with, I'm not sure how that would create SQL rows?

The SRT has to be muxed in either as the video is being created or after it exists, unless there is a way to tell the start and end time of the video before it's finished to be able to do it while the video is being created?

**Comment by moeiscool** [comment]
search `fs.watch`.

We could get the start time but not the end time. Looks like a headache and a half. You will need to add guards that make it so the post burning doesn't interfere.

**Comment by mattdurant** [comment]
If touching the videos folder isn't allowed, then the only option I can see is creating a subtitles folder and writing separate files into it.  At least they would be usable in the html5 video tag and could be burned-in later if needed.  Maybe could mux them in before downloading too?

**Comment by moeiscool** [comment]
yah that's what i was wondering if we could use javascript or something.. if html5 video tag can do it natively then even better. A separate folder would be okay with me, its not like these things take up a lot of space :smile: You can easily see how to add folders to the structure by following the `s.dir.videos` variable.

Maybe we can add the the option to mux and the option to download. I personally would not want an ffmpeg process to spawn every time i downloaded a file.

**Comment by mattdurant** [comment]
I'll add an option to the interface to create subtitle files, I'll create the VTT files in a separate folder, and add them to the video player for now.  I know not having timestamps baked-in was one of the first things I noticed when using copy mode, and it's something that LEO or commercial users would want to see.  Have you had anyone bring up having or not having timestamps on copy mode streams?

**Pull request closed without merging**
