### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by cbrherms**
1. Fixed tables_check that was always returning 0
2. Fixed _mysql function
3. Re-added user and database creation so it can use env variables
4. Removed forced ccio database creation from framework.sql file

### CODE REVIEW

**Comment by moeiscool** [comment]
the changes done to the sql file break the regular install process, please revert the changes to the sql files or update the installers to address this.

Please also make required changes in documentation due to the possible changes of the sql files. https://github.com/ShinobiCCTV/shinobi.video

**Review by moeiscool — CHANGES_REQUESTED** [review]
changes in `sql/framework.sql` break install processes.

**Comment by cbrherms** [comment]
Split framework.sql in to database.sql and tables.sql
Installers and entrypoint edited to reflect this.

**Comment by moeiscool** [comment]
sweet, just saw your post in the other thread. Is there a tutorial somewhere I can adapt a Shinobi docker command line tutorial? I'll do the merge after i run a few tests and write up the docs.

**Comment by cbrherms** [comment]
Primarily you'll want people pulling from your dockerhub repo rather than from source so you'd have to make sure automated builds are set up for each branch with the relevant tags. `latest` `dev` and `kitematic`

A guide..... best bet is looking at guides for phpmyadmin or wordpress as they use linked mysql containers.
The readme's on dockerhub for each official container has a fair amount of information.

End goal will be to have either one command line to use if you're using a mysql host on another machine that's already set up, or two command lines, one to build the mysql container and then another to create a linked shinobi container, including all environment variables that you don't want to be just default.

For setting up a mysql container: [mysql](https://hub.docker.com/r/_/mysql/)

An example app that would use similar linking or use of an external server: [phpmyadmin/phpmyadmin](https://hub.docker.com/r/phpmyadmin/phpmyadmin/)

and an example two lines that would bring up a fully working instance (substituting `cbrherms/shinobi:dev` for `shinobicctv/shinobi:latest` for the moment and using default env variables)


`docker run --name shinobi-db -e MYSQL_ROOT_PASSWORD=rootpass -v /var/lib/mysql:/some/local/folder/mysql -d mysql:8`

`docker run --name shinobi -d --link shinobi-db:mysql -e MYSQL_HOST=shinobi-db -e MYSQL_ROOT_PASSWORD=rootpass -p 8080:8080 -v /opt/shinobi/videos:/some/local/folder/videos cbrherms/shinobi:dev
`

Substitute `/some/local/folder/videos` with a local folder for storing videos.
Substitute `/some/local/folder/mysql` with a local folder for storing your mysql database.

Hope that helps

***
Edited as I forgot the mysql volume for persistence on that container.....

**Comment by ghost** [comment]
Just thinking out loud here.  Adding a nginx container with proxy pass would be pretty awesome. Like wise phpmyadmin on one of them would be handy.

Thanks again!

**Comment by cbrherms** [comment]
This can all be done with a docker compose file.

**Comment by ghost** [comment]
@cbrherms pulled your dev branch and got a temp working install while I wait for @moeiscool .  Thank you

Quick ? if you don't mind. You suggested running two docker run commands to bring it up.  From what I have learned so far after initial docker-compose up I can just docker-compose stop/start and restart to bring it all back up.  I am curious why you suggest those two long docker run commands instead of just docker-compose start.  Won't that just start a one off/spawn two new containers?

Regards

**Comment by cbrherms** [comment]
@wcat13 

Docker-compose is just a way of using docker with a preconfigured config file, where you would edit the `docker-compose.yaml` to set all your environment variables. 

Admittedly i'd interpreted @moeiscool 's request to be that he needed the actual `docker run` way (which is what compose chews out from the config file) as a bit of a deeper explanation of what it actually does. As there'd need to be a guide / explanation to how the containers are run in this way on the dockerhub page [shibobicctv/shinobi](https://hub.docker.com/r/shinobicctv/shinobi/)

**Comment by ghost** [comment]
I am just trying to figure out the best/proper way to achieve persistence, if I am using the correct terminology. I tried adding a volume entry in the yml file but have permission problem.

Also pm2 is failing to start camera.js after I docker-compose restart a few times.  Cannot figure out what causes it because it works fine a few times then decides to fall on it's face. Also I added the motion plugin and pm2 start shinobi-motion.js works but trying to pm2 startup and save fails.

I will pick up on this tom.  Thanks for giving me your time.

```
shinobi    | 1|camera   | uncaughtException { [SyntaxError: Unexpected token ...]
shinobi    | 1|camera   |   stackframes: 
shinobi    | 1|camera   |    [ { file_name: 'vm.js', line_number: 53 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 374 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 417 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 344 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 301 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 354 },
shinobi    | 1|camera   |      { file_name: 'internal/module.js', line_number: 12 },
shinobi    | 1|camera   |      { file_name: '/opt/shinobi/node_modules/nodemailer/lib/nodemailer.js',
shinobi    | 1|camera   |        line_number: 3 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 410 },
shinobi    | 1|camera   |      { file_name: 'module.js', line_number: 417 } ] }
shinobi    | PM2        | App [camera] with id [1] and pid [239], exited with code [0] via signal [SIGINT]
shinobi    | PM2        | Script /opt/shinobi/camera.js had too many unstable restarts (16). Stopped. "errored"

```

**Comment by ghost** [comment]
So to follow up it has something to do with this
https://stackoverflow.com/questions/35525436/cannot-find-module-glob
npm install -g glob
fixes the issue I was having with pm2

**Comment by ghost** [comment]
Scratch that 

```
shinobi    | 1|camera   | { Error: Connection lost: The server closed the connection.
shinobi    | 1|camera   |     at Protocol.end (/opt/shinobi/node_modules/mysql/lib/protocol/Protocol.js:109:13)
shinobi    | 1|camera   |     at Socket.<anonymous> (/opt/shinobi/node_modules/mysql/lib/Connection.js:109:28)
shinobi    | 1|camera   |     at emitNone (events.js:110:20)
shinobi    | 1|camera   |     at Socket.emit (events.js:207:7)
shinobi    | 1|camera   |     at endReadableNT (_stream_readable.js:1045:12)
shinobi    | 1|camera   |     at _combinedTickCallback (internal/process/next_tick.js:102:11)
shinobi    | 1|camera   |     at process._tickDomainCallback (internal/process/next_tick.js:198:9) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' } '' ''
shinobi    | 1|camera   | Error Connecting : DB { Error: connect ECONNREFUSED 172.19.0.2:3306
shinobi    | 1|camera   |     at Object.exports._errnoException (util.js:1026:11)
shinobi    | 1|camera   |     at exports._exceptionWithHostPort (util.js:1049:20)
shinobi    | 1|camera   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
shinobi    | 1|camera   |     --------------------
shinobi    | 1|camera   |     at Protocol._enqueue (/opt/shinobi/node_modules/mysql/lib/protocol/Protocol.js:141:48)
shinobi    | 1|camera   |     at Protocol.handshake (/opt/shinobi/node_modules/mysql/lib/protocol/Protocol.js:52:41)
shinobi    | 1|camera   |     at Connection.connect (/opt/shinobi/node_modules/mysql/lib/Connection.js:130:18)
shinobi    | 1|camera   |     at Object.s.disc (/opt/shinobi/camera.js:78:9)
shinobi    | 1|camera   |     at Connection.<anonymous> (/opt/shinobi/camera.js:79:90)
shinobi    | 1|camera   |     at emitOne (events.js:115:13)
shinobi    | 1|camera   |     at Connection.emit (events.js:210:7)
shinobi    | 1|camera   |     at Connection._handleProtocolError (/opt/shinobi/node_modules/mysql/lib/Connection.js:433:8)
shinobi    | 1|camera   |     at emitOne (events.js:115:13)
shinobi    | 1|camera   |     at Protocol.emit (events.js:210:7)
shinobi    | 1|camera   |   code: 'ECONNREFUSED',
shinobi    | 1|camera   |   errno: 'ECONNREFUSED',
shinobi    | 1|camera   |   syscall: 'connect',
shinobi    | 1|camera   |   address: '172.19.0.2',
shinobi    | 1|camera   |   port: 3306,
shinobi    | 1|camera   |   fatal: true } 
```

lol I am over my head. Gonna  focus on learning docker better because I can't tell whats going on.

You guys have a great day.  I will stop mucking up this thread now.

**Comment by cbrherms** [comment]
Persistence would be achieved by having the mysql config files / database outside of the docker container.

Is this pulled from the dev branch I have? What OS are you running on, and how did you install docker?
Shouldn't have permissions issues editing the `docker-compose.yaml` file.... are you git cloning the repo, or downloading in zip format, or using a third party program such as GitKraken to clone it? 

In work at the moment but i'll try and replicate your process when i'm done

**Comment by ghost** [comment]
No the permission issue was from adding a 'volume:' entry in the compose yaml file.  So when the share was created my user couldnt create inside the container owned by root.  Not with permissions in any of the repo files.  I cloned your repo.  Don't sweat it I am going to be out for the rest of the day. 

I am on elemetary os(ubuntu 16.04) Install from docker repo/followed docker install page for Ubuntu.

If you do mess around with it later try  docker-compose restart/stop/start a couple times and apt update/ add motion plugin.  That is all i really did other than adding a mjpeg camera.  At some point it causes issues with pm2 being able to start camera.js.

**Comment by moeiscool** [comment]
Woah, @wcat13 are you running the docker image from the master repo? If so please try @cbrherms https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=Shinobi&starCount=0 you should get a lot further. If you are re experiencing errors with modules it might be because of the version of node.js you are using. You must be on 7.2.0(+)

**Comment by ghost** [comment]
I was on @cbrherms dev branch.  Also the nodejs version in the container was above 7.20.  Trying to remember....8 or higher.  On first compose up everything was working just fine.  It was restarting the containers or one of the other few things I did where I started to get pm2 startup errors.

**Comment by cbrherms** [comment]
@wcat13 that image was actually using nodejs v4.2.6 it seems. This pull has been updated to correct that. But, from what you've been saying it seems you're installing things within the container once it's brought up? Afraid that's not how docker works. The image gets set up via the `dockerfile`, then configured via environment variables (in your case the `docker-compose.yml`) and external config files. If things need added/installed these need to be done in the dockerfile itself.

Also, with your videos folder, as you're on an Ubuntu base, SELinux may be installed and affecting the permissions on your videos folder. you'll have to append `:z` to the volume variable in the compose file. 
If using default it should look like:
```
    volumes:
      - ./videos:/opt/shinobi/videos:z
```

@moeiscool also committed some more changes that add database persistence to the docker-compose way of pulling it up, and fixed an issue with the config if a container was destroyed rather than stopped.

Would it be possible to get the config examples in the root or an `./example-config` folder, and the files in use in a folder such as `./config` as this would improve things cross platforms and allow these to be kept outside of docker containers as is the standard. Would also then need the motion plugin to pull it's config from this too and would have to have it's name changed as it's currently named the same as the main one.

**Comment by moeiscool** [comment]
>Would it be possible to get the config samples in the root, and the files in use in a folder such as ./config as this would improve things cross platforms and allow these to be kept outside of docker containers as is the standard. Would also then need the motion plugin to pull it's config from this too and would have to have it's name changed as it's currently named the same as the main one.

I considered this a little while ago (before super.json) I didn't do it because i need to have the conf.json for a plugin with the .js file. I plan to run a separate node to do all motion and object detection. That's pretty much why I have plugins interface shinobi with socket.io rather than do an include.

@wcat13 you can run this to update node.js
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by ghost** [comment]
@cbrherms I just got rid of the image I had and pulling yours now to be sure and I plan to use moes dev. I will add all the junk to enable motion plugin to bottom of Dockerfile.  This sound correct?  I am fairly positive the version of node in the container I was running was 8, no matter, container and image is gone now.  I did notice that the ffmpeg version was lower than the recommended 3x.  So correct me if I am wrong, I would need to add all the steps to remove ffmpeg and add the prebuilt packages from within the Dockerfile?  Not allowed to do it from within container(that seem so strange to me btw).  I have a real love hate relationship with Docker at the moment. Thank you

**Comment by ghost** [comment]
OK I am at least seeing my mistakes now.  I have cbherms dev image and using his dev github repo. Sadly this is how I learn...

I added what I wanted to to the Dockerfile like so

```
RUN apt update \
    && apt install -y curl \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash \
    && apt install --no-install-recommends -y ffmpeg nodejs libav-tools \
    wget mysql-client \
    && rm -rf /var/lib/apt/lists/* \
    && cp /opt/shinobi/conf.sample.json /opt/shinobi/conf.json \
    && cp /opt/shinobi/super.sample.json /opt/shinobi/super.json \
    && npm install \
    && npm install pm2 -g \
    && chmod +x ./docker-entrypoint.sh \
    && cp /opt/shinobi/plugins/motion/conf.sample.json /opt/shinobi/plugins/motion/conf.json \
    && apt update && apt install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ -y \
    && npm install canvas \
    && cd plugins/motion \
    && pm2 start shinobi-motion.js \
    && pm2 save

```
I also added new mysql passwords and volume: info to .yml
I used
```
    volumes:
      - ~/Videos:/opt/shinobi/videos:z

```
Which is a little different than your suggestion.  The videos share/mount is working but my host user still does not have write permission. So I will have to look into that.

My 3 year old is acting bad word police sitting behind me while I try to get this sucker to build.  "Bad word Daddy" lol

So I am up and running. ffmpeg version is 2.8.11 and that pm2 shinobi-motion.js start and save gets removed by something in docker-entrypoint.sh so I had to restart it.    node -v returns v8.0.0.

Im getting closer. I very much appreciate the input/effort.

**Comment by cbrherms** [comment]
The container runs as root and any files it creates will be owned by root, so you should be able to write to to it if you prep-end your commands with `sudo` as the host user.
You can confirm this by typing in `ls -al ~/Videos`.
But yes, On a volume declaration the left side is your local folder so you can change that to anything you want.


As for your dockerfile.... change this:
```
    && cp /opt/shinobi/plugins/motion/conf.sample.json /opt/shinobi/plugins/motion/conf.json \
    && apt update && apt install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ -y \
    && npm install canvas \
    && cd plugins/motion \
    && pm2 start shinobi-motion.js \
    && pm2 save
```

To this:
```
    && cp /opt/shinobi/plugins/motion/conf.sample.json /opt/shinobi/plugins/motion/conf.json \
    && apt install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ -y \
    && npm install canvas
```

Then at the end of  the `docker-entrypoint.sh` you must uncomment the line that currently looks like:
`# pm2 start "${SHIN_BIN_DIR}/plugins/motion/shinobi-motion.js"`


Over the weekend i'm going to have a look through all the dependencies and make sure they meet min specs, including ffmpeg, and at least look at getting plugins installed as standard. Also have a couple of ideas for better config persistence too.


@moeiscool can we lay off the merge for a bit? May as well get the docker implementation up to scratch fully before bringing it in.

**Comment by ghost** [comment]
@cbrherms had to 
```
    && cp /opt/shinobi/plugins/motion/conf.sample.json /opt/shinobi/plugins/motion/conf.json \
    && apt update && apt install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ -y \
    && npm install canvas
```
apt cache gets deleted here
```
&& rm -rf /var/lib/apt/lists/*
```
so
```
&& apt update && apt install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ -y 
```
was necessary.

I also added
```
      - /etc/localtime:/etc/localtime:ro
```
For both containers to fix timezone discrepancies.  Otherwise working great. Really like docker-compose.

Thanks again for all your insight.

**Comment by cbrherms** [comment]
@wcat13 
Whoopsie, I missed that one! 
But, as these are changes and improvements that go a bit beyond what this pull was aiming to achieve, even though relevant to this docker development pull, i'm going to create a new branch to implement the suggestions and leave this one as is to save all the notifications @moeiscool must be getting.

As it stands, this pull is now at the stage where you can get a working barebones docker installation as is, with persistence on the database. 
So long as this achieves those goals and passes testing I believe it should be ready to commit. Obviously if there's any actual faults i'll make the necessary commits before merging.

@wcat13 i'll be adding the plugins and making further docker changes on my dev2 branch if you'd like to follow it. Any issues raise them on my own repo with an issue ticket.

**Comment by ghost** [comment]
Don't forget to update ffmpeg. Moe has link to a nice drop in http://shinobi.video/docs/start#setup_ubuntu_hard

**Comment by michaelarnauts** [comment]
The framework.sql (edit: now database.sql) file seems to use `ccio` as database name, but the docker-compose specified `shinobi-db`.

Also, the `shinobi` container itselfs also contains a mysql-server.

**Comment by ghost** [comment]
Hi @michaelarnauts from what I can make of it is if we use docker-compose up it will create the databases according to what is in the yml file.

Correct me if I am wrong(I probly am)

I think there is only the one mariadb container/sql server in play and it is linked to shinobi container.  So that you can run mysql commands from shinobi.

I threw phpmyadmin container into the mix and can only log into the mariadb container with the creds I used in my yaml file.

What I did was fairly easy to do.

I pulled the official phpmyadmin image from docker hub.
```
docker pull phpmyadmin/phpmyadmin
```
Then I added this to yml
```
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - database
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_ARBITRARY: 1

volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local
```
Grab the ip addr of the shinobi-db conatiner
```
docker exec -it shinobi-db bash
ip addr
```
then hit localhost:8081
enter the ip and root creds.

This is using @cbrherms dev image and his github repo dev branch.

Either way having phpmyadmin is way easier for me.

**Comment by michaelarnauts** [comment]
@wcat13 correct.

You can define ENV vars in docker-compose.yml, and the mysql container will use these to create a database. You can also map a folder with sql files to it, and it will execute them one by one the first time the container is started.

You don't need to link it in the docker-compose.yml file, that's done automatically. The `shinobi` container can reach the mysql container by contacting `shinobi-db`. Docker will resolve this to the correct ip of the container.

The issue is that the docker-compose.yml file specifies a `MYSQL_DATABASE=shinobi` line, so the mysql container will create a `shinobi` db when starting up. Then, the `shinobi` container will create a `ccio` database.

These names could be better aligned, so that docker-compose.yml makes sure the right database is created before `shinobi` starts creating tables. This can be done like it is now, by simply waiting untill the mysql server is reachable (since the `shinobi` container can be ready before mysql is done starting up). The file `sql/database.sql` isn't needed then anymore (edit: for Docker that is, the CENTOS and UBUNTU install scripts might still want it).

**Comment by cbrherms** [comment]
@michaelarnauts 
Yes, `sql/database.sql` will need to remain for the ubuntu and centos installs.

I see what you mean though. But, as can be seen within the `docker-entrypoint.sh` in this pull it does not use `sql/database.sql` anymore and instead directly creates the database if it doesn't exist with the line:
`    _mysql -e "CREATE DATABASE IF NOT EXISTS \'$MYSQL_DATABASE\' ;"`
and then modifies the config to suit.
The database creation needs to stay within the image entrypoint for the purpose of allowing people to use external databases. 

One thing i have noticed, is that the defaults within `docker-compose.yml` need to be brought in line with the defaults in both the `dockerfile` and `docker-entrypoint.sh` to limit any confusion.

In my `dev2 `branch i've removed the unnecessary mysql database ENV vars and left it to just the MYSQL_ROOT_PASSWORD
(edit: looks like i haven't pushed that up yet. whoops)(edit2: done)

Just pushed a commit to this pull with those changes. Were there any other suggestions?

@wcat13  michael is correct, you no longer need to use `links:` though you can change that to `depends_on:` to make sure phpmyadmin is brought up after the database.

**Pull request closed without merging**
