### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by pschmitt**
This PR builds upon @simonoff changes (https://github.com/moeiscool/Shinobi/pull/143) and brings some minor extra changes regarding image size and docker-compose shenanigans.

The one big change this introduces is better docker-compose support and it fixes the persistence issue.
To start Shinobi a simple `docker-compose up` is enough.

Data persistence can be obtained by using standard Docker volumes.
[HERE](https://gist.github.com/pschmitt/52090e8a862d308d1d7f156665bf2520) is an example docker-compose file that does exactly that.

Related issues: 
- https://github.com/moeiscool/Shinobi/issues/125

### CODE REVIEW

**Comment by moeiscool** [comment]
do you have an image on dockerhub i can test with kitematic? can i add something to Dockerfile to run `docker-compose up`?

**Comment by pschmitt** [comment]
You cannot "add something to Dockerfile to run docker-compose up", that's just not how this works.
This won't work out of the box with Kitematic, not untill https://github.com/docker/kitematic/issues/137 gets implemented.
The changes this PR brings is that it actually removes the internal MySQL server.
What you could do if you really insist on using kitematic is spinning up a `mysql` container and `pschmitt/shinobi:docker-compose` and link them both.

**But you should really read into docker-compose, it is a standard tool in the Docker world.**

**Comment by moeiscool** [comment]
i see, that makes sense. ill try it out. I don't use docker myself but ill try to follow the standards if i'm going to include the installer. thx :)

**Comment by ghost** [comment]
Hello @moeiscool & @pschmitt 
I ran docker-compose up and was able to get the log in screen but received a bunch of ernno sql table does not exist errors and unable to login.  My Docker foo is quite weak but looking through the files I am assuming that docker-compose up should have gotten me a working installation with two containers(shinobi & mysql).

I am on ubuntu xenial, no fancy front end to docker.
 
Am I correct to assume running docker-compose up should get me a working install?
Which files should I edit if I want to change mysql usernames and passwords pre docker-compose up?

Thank you for this software I ran it successfully with the virtualbox image(version inside very outdated and missing key aspects such as motion plugin btw).  I renamed shinobi folder in virtual machine then git cloned and it seemed to update fine.  I would much prefer the docker version over the VM resource wise. I am just unsure of what needs to be done to get  compose up to work.
any help appreciated

Best Regards

**Comment by moeiscool** [comment]
I'm kind of useless when it comes to docker but I did come across something that might help.

A docker image put together by @cbrherms https://hub.docker.com/r/cbrherms/shinobi/

He has made a pull request addressing some issues with the docker but I haven't gotten around to testing and merging yet. You can see the pull request here https://github.com/moeiscool/Shinobi/pull/175

I hope that helps, if not then perhaps @pschmitt has some thoughts on it.

----
There are actually a few images and also one from @pschmitt https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=Shinobi&starCount=0

**Comment by cbrherms** [comment]
@wcat13 if i remember right that will be due to the fact that the compose file specifies MYSQL_DATABASE as "shinobi" yet during the initialisation of the shinobi part it creates the shinobi database, then at the table injection stage creates a database called ccio and injects the tables in there instead.

About to run a quick test docker-compose up on both pre and post pull request to see if this is corrected by the changes to the framework.sql setup (which can be found on my dev tagged fork)

***

Just got around to testing and with the hopefully merging PR #175 "docker-compose up" from root folder will get you a fully working installation out of the box.

MySQL username and passwords are edited in the `environment:` sections of docker-compose.yml and are prepopulated with the defaults.

Remember that if you change a variable it must be the set the same within both the `shinobi:` and `mysql:` sections.

**Comment by cbrherms** [comment]
@wcat13 Just got around to testing and with the hopefully merging PR #175 "docker-compose up" from root folder will get you a fully working installation out of the box.

MySQL username and passwords are edited in the `environment:` sections of docker-compose.yml and are prepopulated with the defaults.

Remember that if you change a variable it must be the set the same within both the `shinobi:` and `mysql:` sections.

**Comment by pschmitt** [comment]
The reason this does not work anymore is that this https://github.com/moeiscool/Shinobi/commit/c39ee49713f6dd00ce0df94e9d8d27404205b44d was merged.

**Comment by ghost** [comment]
Thanks guys. Very much appreciated. I am really impressed with the work you have done thus far @moeiscool . 

Morning @pschmitt It is going to be a few days until I have some 'me' time to do what I want to do.

Thanks again for quick replies.

**Comment by pschmitt** [comment]
The main issue here is that the database is hardcoded in [sql/framework.sql](https://github.com/moeiscool/Shinobi/blob/master/sql/framework.sql#L15).
We should either write a custom script that accepts parameters or do some sed foo in `docker-entrypoint.sh`.

**Comment by cbrherms** [comment]
Not after my PR. I removed the database creation from that and instead put them back in `docker-entrypoint.sh`

Should just leave the install scripts for Ubuntu and Centos to do once that's merged?

**Comment by pschmitt** [comment]
The database creation is unnecessary IMHO since both mariadb and mysql already create a database on init.

**Comment by moeiscool** [comment]
@pschmitt the reason I reverted the sql files was because the changes broke the other install processes. As much as I'd like docker to work, I need the baremetal installations to work more.

Sorry @cbrherms I haven't gotten around to testing your PR yet. Docker has made me weary.

For all looking to use docker at this time please use @cbrherms or @pschmitt images for now.

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=Shinobi&starCount=0

**Comment by cbrherms** [comment]
@pschmitt  Yes, mariadb and mysql will create create the databases on init IF you add the relevant env var to it on running, eg using a docker-compose file with the relevant linking. But the point is I wanted to make a image that would work for the multiple different scenarios that it could be used in.
I personally use docker with compose configs at work, with a premade mysql server we have on site, command line on my main machine at home but use kitematic to monitor running containers, and FreeNAS Corral's experimental implementation of docker on my media server.
With the Dockerfile how it is in the PR, it'll set up the database if it doesn't exist in all of these scenarios. Can't really put the pressure on an end user having the know-how to set up the mysql instance properly if using a method other than docker-compose, so this should cater for all wouldn't you think? Would still leave the more advanced users such as yourself to add in whatever variables you want, plus won't affect the baremetal installs.

@moeiscool  No worries.

**Pull request merged**
